export enum ErrorCode {
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
  UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT",
  LIBREOFFICE_NOT_FOUND = "LIBREOFFICE_NOT_FOUND",
  PYTHON_NOT_FOUND = "PYTHON_NOT_FOUND",
  LIBREOFFICE_UNO_CONVERSION_FAILED = "LIBREOFFICE_UNO_CONVERSION_FAILED",
  LIBREOFFICE_CLI_CONVERSION_FAILED = "LIBREOFFICE_CLI_CONVERSION_FAILED",
  PDF_RENDER_TOOL_NOT_FOUND = "PDF_RENDER_TOOL_NOT_FOUND",
  PDF_RENDER_FAILED = "PDF_RENDER_FAILED",
  EXCEL_TEXT_EXTRACTION_FAILED = "EXCEL_TEXT_EXTRACTION_FAILED",
  WORD_TEXT_EXTRACTION_FAILED = "WORD_TEXT_EXTRACTION_FAILED",
  COPILOT_CLI_NOT_FOUND = "COPILOT_CLI_NOT_FOUND",
  GITHUB_TOKEN_MISSING = "GITHUB_TOKEN_MISSING",
  COPILOT_MARKDOWN_FAILED = "COPILOT_MARKDOWN_FAILED",
  INVALID_TOOL_INPUT = "INVALID_TOOL_INPUT",
}

export class AppError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly context?: Record<string, unknown>
  ) {
    super(message);
    this.name = "AppError";
  }
}
